name: FORCE-EDA
channels:
  - conda-forge
  - defaults
dependencies:
  - pandas
  - numpy
  - python=3.7.7
  - matplotlib
  - scikit-learn
  - s3fs
  - pip
  - pip:
      - missingno
      - cegaltools